name: Email Notification to commit user
on:
  push:
  pull_request:
    branches:
      - main          # Can be changed to master
      #- feature/test  # Can be changed to your feature branch for tests

jobs:
  Notification-to-Commit-User:
    runs-on: ubuntu-latest
    env:
        NOTIFICATION_SMTP_USER: ${{secrets.SMTP_USER}}
        NOTIFICATION_SMTP_PASSWORD: ${{secrets.SMTP_PASSWORD}}
        NOTIFICATION_FROM: ALVDIGITAL Systems (API)
        NOTIFICATION_SUBJECT: ALV API Controllers-GitHub Updated
        #NOTIFICATION_TO_DEFAULT: vijaik.nd@gmail.com, vishali.nagathevan@gmail.com #kumvijaya@gmail.com # service@alvdigital.com
        NOTIFICATION_EMAIL_RECIPIENTS: vijaik.nd@gmail.com, vishali.nagathevan@gmail.com #service@alvdigital.com,kumvijaya@gmail.com

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: To get username and email id
        id: usr-mail-info
        run: |
          username_html=''
          email_id_html=''

          username=$(git log -n 1 --pretty=format:%an)
          email_id=$(git log -n 1 --pretty=format:%ae)

          #echo "$username username"
          #echo "$email_id email_id-Hello"

          username=$(echo "${username//$'\n'/<br />}")
          email_id=$(echo "${email_id//$'\n'/<br />}")

          username_html="${username}"
          echo "username_html=$username_html" >> $GITHUB_OUTPUT

          email_id_html="${email_id}"
          echo "email_id_html=$email_id_html" >> $GITHUB_OUTPUT

      - name: Send notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{env.NOTIFICATION_SMTP_USER}}
          # Optional (recommended) mail server password:
          password: ${{env.NOTIFICATION_SMTP_PASSWORD}}
          # Required mail subject:
          subject: ${{ env.NOTIFICATION_SUBJECT }}
          # Required recipients addresses:
          to: ${{ steps.usr-mail-info.outputs.email_id_html }} #${{ env.NOTIFICATION_TO_DEFAULT }}
          # Optional blind carbon copy recipients:
          bcc: ${{ env.NOTIFICATION_EMAIL_RECIPIENTS }}
          # Required sender full name (address can be skipped):
          from: ${{ env.NOTIFICATION_FROM }}
          # Optional plain body:
          html_body: |
            <p>
            Hi <b>${{ steps.usr-mail-info.outputs.username_html }}</b> <br><br>  
           
            You committed to master. <br><br>
            
            Do not forget to: <br>
            - inform your colleagues in the Skype "New on Live" group <br>
            - create a Help Center ticket in Jira (usually required) <br>
            - create a GI ticket in Jira (usually required) <br><br>
            
            To create tickets in Jira, from within the ALVCODE project, please use the Automation Action on the right             
            "Create Help Center / GI tickets" as shown below: <br><br>
            
            WHAT IMAGE ... NEED TO DISCUSS WITH VK <br><br>

            Please do this now! <p>
            

          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: high
          # Optional HTML body read from file:
          #html_body: file://README.html
          # Optional carbon copy recipients:
          #cc: service@alvdigital.com,kumvijaya@gmail.com
          # Optional recipient of the email response:
          #reply_to: service@alvdigital.com,kumvijaya@gmail.com
          # Optional Message ID this message is replying to:
          #in_reply_to: service@alvdigital.com,kumvijaya@gmail.com
          # Optional unsigned/invalid certificates allowance:
          #ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          # convert_markdown: true
          # Optional attachments:
          #attachments: attachments.zip,git.diff,./dist/static/*.js